<?php

namespace Plugin\StripeRec\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\StripeRec\Entity\RecCsv;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecCsvRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, RecCsv::class);
    }

    public function getAll()
    {
        return $this->createQueryBuilder('rc')
            ->select('rc')
            ->orderBy('rc.sort_no', 'asc')
            ->getQuery()
            ->getResult();
    }
}
