<?php

namespace Plugin\StripeRec\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\StripeRec\Entity\StripeRecShippingProduct;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripeRecShippingProductRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, StripeRecShippingProduct::class);
    }

    /**
     *
     * @return null|StripeRecShippingProduct
     */
    public function get()
    {
        $conf = $this->findBy([]);
        if(count($conf) == 0){
            return null;
        }
        return $conf[0];

    }
}
